import { z } from "zod";

export const eventParamsSchema = z.object({
  id: z.string().min(1),
});

/** Accepts an ISO string over the wire and hands the handlers a Date. */
const dateFromIso = z.iso.datetime({ offset: true }).pipe(z.coerce.date());

/** Filenames are generated by the upload endpoint; reject anything path-like. */
const imageKeySchema = z
  .string()
  .regex(/^[a-z0-9]+\.(jpg|jpeg|png|webp|gif)$/i, "Invalid image key");

export const createEventSchema = z.object({
  name: z.string().min(1).max(255),
  description: z.string().max(2000).nullish(),
  /** Links to an existing Address; null detaches the venue. */
  addressId: z.string().min(1).nullish(),
  imageKey: imageKeySchema.nullish(),
  startsAt: dateFromIso.nullish(),
  endsAt: dateFromIso.nullish(),
});

export const updateEventSchema = createEventSchema.partial();

export const eventResponseSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  addressId: z.string().nullable(),
  imageKey: z.string().nullable(),
  startsAt: z.date().nullable(),
  endsAt: z.date().nullable(),
  createdAt: z.date(),
  updatedAt: z.date(),
});
