import { z } from "zod";

/**
 * Shared request contracts. Deliberately a single module with no relative
 * imports: the package ships raw TypeScript, and NodeNext (the API) and
 * Turbopack (the web app) disagree about how to resolve `./x.js` specifiers
 * against `.ts` files. Nothing to resolve means both are satisfied.
 */

// ---------------------------------------------------------------- addresses

export const addressParamsSchema = z.object({
  id: z.string().min(1),
});

/** line1, city and country are NOT NULL in the database. */
export const createAddressInput = z.object({
  label: z.string().max(255).nullish(),
  line1: z.string().min(1).max(255),
  line2: z.string().max(255).nullish(),
  city: z.string().min(1).max(255),
  region: z.string().max(255).nullish(),
  postalCode: z.string().max(32).nullish(),
  country: z.string().min(1).max(255),
});

export const updateAddressInput = createAddressInput.partial();

export type CreateAddressInput = z.infer<typeof createAddressInput>;
export type UpdateAddressInput = z.infer<typeof updateAddressInput>;

// ------------------------------------------------------------------- events

export const eventParamsSchema = z.object({
  id: z.string().min(1),
});

/** Filenames are generated by the upload endpoint; reject anything path-like. */
export const imageKeySchema = z
  .string()
  .regex(/^[a-z0-9]+\.(jpg|jpeg|png|webp|gif)$/i, "Invalid image key");

/** Turns an ISO string into a Date. Server-side only. */
const dateFromIso = z.iso.datetime({ offset: true }).pipe(z.coerce.date());

/**
 * One field shape, two schemas derived from it: the browser works in strings,
 * the server wants Date objects. Deriving both from here means the non-date
 * rules cannot drift apart.
 */
const eventFields = {
  name: z.string().min(1).max(255),
  description: z.string().max(2000).nullish(),
  /** Links to an existing Address; null detaches the venue. */
  addressId: z.string().min(1).nullish(),
  imageKey: imageKeySchema.nullish(),
  startsAt: z.iso.datetime({ offset: true }).nullish(),
  endsAt: z.iso.datetime({ offset: true }).nullish(),
};

/** Wire shape — what the form validates against. */
export const createEventInput = z.object(eventFields);
export const updateEventInput = createEventInput.partial();

/** Server shape — what the API parses request bodies with. */
export const createEventPayload = createEventInput.extend({
  startsAt: dateFromIso.nullish(),
  endsAt: dateFromIso.nullish(),
});
export const updateEventPayload = createEventPayload.partial();

export type CreateEventInput = z.infer<typeof createEventInput>;
export type UpdateEventInput = z.infer<typeof updateEventInput>;
export type CreateEventPayload = z.infer<typeof createEventPayload>;
export type UpdateEventPayload = z.infer<typeof updateEventPayload>;

export { ZodError } from "zod";
export { z };
